version: '3.5'

services:
    backend:
        image: land_backend:latest
        container_name: land_backend
        build:
            context: ./backend
        environment:
            - NODE_ENV=development
            - DB_URL=http://land:land@couchdb:5984  
        command: ["sh","-c","yarn install && yarn start"]

        volumes:
            - yarn-cache:/home/node/.yarn
            - /usr/src/backend/node_modules
            - ./backend:/usr/src/backend:rw,cached            
        ports: 
            - 4000:4000   

    frontend:
        image: land_frontend:latest
        container_name: land_frontend
        build:
            context: ./frontend  
        environment:
            - NODE_ENV=development
            - REACT_APP_API_URL=http://localhost:4000/

        command: ["sh","-c","yarn install && yarn start"]
        volumes:
            - yarn-cache:/home/node/.yarn
            - /usr/src/frontend/node_modules
            - ./frontend:/usr/src/frontend:rw,cached    
        ports: 
            - 3000:3000             

    couchdb:
        image: couchdb:latest
        container_name: land_db
        environment: 
            - COUCHDB_USER=land
            - COUCHDB_PASSWORD=land
        ports:
            - 5984:5984

volumes:
    yarn-cache:
        driver: local         
   
